### ISSUE TITLE
errs in documentation

### ISSUE THREAD

**Issue by podanypepa** [ourigen/skyline.vim#1]
# 1

in `README` `let g:skyline_fileformat = 0`
in `/doc/skyline.txt` `let g:skyline_file_format = 0`

**README is correct**

# 2

in `README` `let g:skyline_encoding = 0`
in `/doc/skyline.txt` `let g:skyline_show_encoding = 0`

**README is correct**

**Comment by ourigen** [comment]
@podanypepa Just fixed. Thanks for catching the errors!
