### ISSUE TITLE
option to change colors

### ISSUE THREAD

**Issue by ghost** [ourigen/skyline.vim#3]
can you give an option to change color of the status line, the default color is nice it doesn't get in your way, but an option to change it will be nice, thanks.

**Comment by ourigen** [comment]
Hey there, thanks for using my plugin! I haven't had time to work on this, so it likely won't be added for a while. However, you can manually change the color by editing `plugin/skyline.vim`

To do so, you change the highlight-group name (the text between `%#...#`). So for example, let's say the "NORMAL" block is themed by `%#String#` (the `String` highlight-group), which happens to be green in your colorscheme. If you want it to be red instead, then we can change it to a highlight-group that's red, like `Error` for example. This would become `%#String#` -> `%#Error#`

If you need more help, let me know. Hope this can suffice for the meanwhile

**Comment by ghost** [comment]
thanks for getting back to me. your suggestion did the trick i was able to change the colors to my liking 
by the way i love this plugin, there's a lot a of bloated ones out there but this one is simple by design please keep it maintained if you can.
